<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="CI-L100-20" failures="2" tests="2" name="ErrorValidation2" time="11.898" errors="0" timestamp="2024-03-01T16:20:10 IST">
  <testcase classname="Practice.EcommerceWebsite.Tests.ErrorValidation" name="ErrorCheck1" time="0.877">
    <failure type="java.lang.AssertionError" message="expected [] but found [Incorrect email or password.]">
      <![CDATA[java.lang.AssertionError: expected [] but found [Incorrect email or password.]
at Practice.EcommerceWebsite.Tests.ErrorValidation.ErrorCheck1(ErrorValidation.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- ErrorCheck1 -->
  <testcase classname="Practice.EcommerceWebsite.Tests.ErrorValidation" name="ErrorCheck2" time="3.012">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Practice.EcommerceWebsite.Tests.ErrorValidation.ErrorCheck2(ErrorValidation.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- ErrorCheck2 -->
</testsuite> <!-- ErrorValidation2 -->
